//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.Resources.Questions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BreachOne {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BreachOne() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication3.Resources.Questions.BreachOne", typeof(BreachOne).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 #include&lt;stdio.h&gt;
        ///2 #include&lt;conio.h&gt;
        ///3 #include&lt;math.h&gt;
        ///4 void main(){
        ///5 double n,i,sum=0;
        ///6 int j;
        ///7 clrscr();
        ///8 printf(&quot;Enter the number of terms:\n&quot;);
        ///9 scanf(&quot;%lf&quot;,&amp;n);
        ///10 for(i=1,j=1;i&lt;=n,j&lt;=n;i++,j++) {
        ///11  sum=sum+(pow(-1,i+1)*(1/i));
        ///12 if(i==1)
        ///13    printf(&quot;\n 1 -&quot;);
        ///14    printf(&quot; (1/%.2lf)  &quot;,i);
        ///15  else if(j%2==0)
        ///16    printf(&quot; (1/%.2lf) + &quot;,i);
        ///17  else
        ///18    printf(&quot; (1/%.2lf) - &quot;,i);
        ///19 }
        ///20 printf(&quot; = %.2lf&quot;,sum);
        ///21 getch();
        ///22 }.
        /// </summary>
        internal static string q1 {
            get {
                return ResourceManager.GetString("q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to else if(i==n).
        /// </summary>
        internal static string q1Code {
            get {
                return ResourceManager.GetString("q1Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14.
        /// </summary>
        internal static string q1LineNo {
            get {
                return ResourceManager.GetString("q1LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of terms:
        ///5
        /// 1 - (1/2.00) +  (1/3.00) -  (1/4.00) +  
        ///(1/5.00)   = 0.78.
        /// </summary>
        internal static string q1Output {
            get {
                return ResourceManager.GetString("q1Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string q1TotalLines {
            get {
                return ResourceManager.GetString("q1TotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	#include&lt;stdio.h&gt;
        ///2.	#include&lt;conio.h&gt;
        ///3.	#include&lt;math.h&gt;
        ///4.	double fact(double n);
        ///5.	void main()
        ///6.	{
        ///7.	 double n,i,x,sum=0;
        ///8.	 int j;
        ///9.	 clrscr();
        ///10.	 printf(&quot;Enter value of x:\n&quot;);
        ///11.	 scanf(&quot;%lf&quot;,&amp;x);
        ///12.	 printf(&quot;Enter the number of terms:\n&quot;);
        ///13.	 scanf(&quot;%lf&quot;,&amp;n);
        ///14.	 printf(&quot;%.2lf&quot;,x);
        ///15.	 for(i=1,j=1;i&lt;=n,j&lt;=n;i=i+2,j++)
        ///16.	{
        ///17.	  sum=sum+(pow(-1,j+1)*pow(x,i))/fact(i);
        ///18.	 }
        ///19.	 printf(&quot; %.2lf&quot;,sum);
        ///20.	 getch();
        ///21.	}
        ///22.	{
        ///23.	 if(n==0)
        ///24.	 {
        ///25.	  retur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q2 {
            get {
                return ResourceManager.GetString("q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to double fact(double n).
        /// </summary>
        internal static string q2Code {
            get {
                return ResourceManager.GetString("q2Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.
        /// </summary>
        internal static string q2LineNo {
            get {
                return ResourceManager.GetString("q2LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value of x:
        ///5
        ///Enter the number of terms:
        ///5
        ///0.09.
        /// </summary>
        internal static string q2Output {
            get {
                return ResourceManager.GetString("q2Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string q2TotalLines {
            get {
                return ResourceManager.GetString("q2TotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	# include &lt;stdio.h&gt;
        ///2.	# include &lt;conio.h&gt;
        ///3.	void main()
        ///4.	{
        ///5.	int r, i, j, c = 1 ;
        ///6.	clrscr() ;
        ///7.	printf(&quot;Enter the number of rows : &quot;) ;
        ///8.	scanf(&quot;%d&quot;, &amp;r) ;
        ///9.	printf(&quot;\nFloyd&apos;s triangle is : \n\n&quot;) ;
        ///10.	for(i = 0 ; i &lt; r ; i++)
        ///11.	{
        ///12.	for(j = 0 ; j &lt;= i ; j++)
        ///13.	{
        ///14.	printf(&quot;%-6d&quot;, c) ;
        ///15.	}
        ///16.	printf(&quot;\n\n&quot;) ;
        ///17.	}
        ///18.	getch() ;
        ///19.	}.
        /// </summary>
        internal static string q3 {
            get {
                return ResourceManager.GetString("q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c++;.
        /// </summary>
        internal static string q3Code {
            get {
                return ResourceManager.GetString("q3Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string q3LineNo {
            get {
                return ResourceManager.GetString("q3LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of rows : 5
        ///
        ///Floyd&apos;s triangle is :
        ///
        ///             1
        ///
        ///          2     3
        ///
        ///       4     5     6
        ///
        ///     7     8     9     10
        ///
        ///11    12    13    14    15.
        /// </summary>
        internal static string q3Output {
            get {
                return ResourceManager.GetString("q3Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19.
        /// </summary>
        internal static string q3TotalLines {
            get {
                return ResourceManager.GetString("q3TotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	#include&lt;stdio.h&gt;
        ///2.	#include&lt;conio.h&gt;
        ///3.	void main()
        ///4.	{
        ///5.		float x, sum, term, denr;
        ///6.		int i, n;
        ///7.		clrscr();
        ///8.		printf(&quot;enter the Value of x and (n) 
        ///   Number of terms to be sum \t :&quot;);
        ///9.		scanf(&quot;%f %d&quot;, &amp;x, &amp;n);
        ///10.		sum =1; term = 1;		
        ///11.		{
        ///12.		  denr = (2*i)*(2*i-1);
        ///13.		  term = -term*x*x/denr;
        ///14.		  sum =sum+ term;
        ///15.		}
        ///16.		printf(&quot;\nthe sum = %f\nNumber
        ///    of terms = %d\nvalue of x = %f\n&quot;,sum,n,x);
        ///17.		getch();
        ///18.	}.
        /// </summary>
        internal static string q4 {
            get {
                return ResourceManager.GetString("q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for(i=1;i&lt;n;i++).
        /// </summary>
        internal static string q4Code {
            get {
                return ResourceManager.GetString("q4Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        internal static string q4LineNo {
            get {
                return ResourceManager.GetString("q4LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter the Value of x and (n) Number of 
        ///terms to be sum   :5
        ///5
        ///the sum = 2.528397
        ///Number of terms = 5
        ///value of x  = 5.000000.
        /// </summary>
        internal static string q4Output {
            get {
                return ResourceManager.GetString("q4Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string q4TotalLines {
            get {
                return ResourceManager.GetString("q4TotalLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.	# include &lt;stdio.h&gt;
        ///2.	# include &lt;conio.h&gt;
        ///3.	void main()
        ///4.	{
        ///5.	int b, p, q, r, x ;
        ///6.	clrscr() ;
        ///7.	b = 1 ;
        ///8.	q = 0 ;
        ///9.	printf(&quot;Enter the number of rows : &quot;) ;
        ///10.	scanf(&quot;%d&quot;, &amp;p) ;
        ///11.	printf(&quot;\nPascal&apos;s triangle is : \n\n&quot;) ;
        ///12.	while (q &lt; p)
        ///13.	{
        ///14.	for(r = 40 - 3 * q ; r &gt; 0 ; --r)
        ///15.	printf(&quot; &quot;) ;
        ///16.	for(x = 0 ; x &lt;= q ; ++x)
        ///17.	{	
        ///18.	b = 1 ;
        ///19.	else
        ///20.	b = (b * (q - x + 1)) / x ;
        ///21.	printf(&quot;%6d&quot;, b) ;
        ///22.	}
        ///23.	printf(&quot;\n\n&quot;) ;
        ///24.	++q ;
        ///25.	}
        ///26.	getch() ;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string q5 {
            get {
                return ResourceManager.GetString("q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if((x==0)||(q==0)).
        /// </summary>
        internal static string q5Code {
            get {
                return ResourceManager.GetString("q5Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18.
        /// </summary>
        internal static string q5LineNo {
            get {
                return ResourceManager.GetString("q5LineNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the number of rows : 5
        ///
        ///Pascal&apos;s triangle is :
        ///
        ///            1
        ///         1     1                             
        ///      1    2     1
        ///  1     3     3     1
        ///1   4     6     4     1.
        /// </summary>
        internal static string q5Output {
            get {
                return ResourceManager.GetString("q5Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27.
        /// </summary>
        internal static string q5TotalLines {
            get {
                return ResourceManager.GetString("q5TotalLines", resourceCulture);
            }
        }
    }
}
